name: Fetch latest blog posts

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "github-stats[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
          feed_list: "https://www.lucasjosino.com/rss.xml"
          date_format: "mmm d, yyyy"
          item_exec: |
            post.thumb = item.enclosure.url
            console.log(post)
            console.log(item)
            console.log(item.enclosure.url)
          template: |
            <tr>
                <td>
                  <a href="$url"><img width="300px" src="$thumb"></a>
                </td>
                <td>
                  <b>$title</b>
                  <br/>
                  <a href="https://www.lucasjosino.com/blog/tags/$categories" alt="See more posts from category: $categories">
                    <b>$categories</b>
                  </a>
                  • 
                  $date
                  <br/>
                  <i>$description</i>
                  <br/>
                  <a href="$url" alt="Read post: $title">Read more ➜</a>
                  </td>
            </tr>
